mxcube/mxcubecore

- Command/Tine.py
- CommandContainer.py
- HardwareObjects/InstanceServer.py
- HardwareRepositoryBrowser.py
Some small changes in HardwareRepository to be able to run qt3/qt4.
- removed qt at all
- added Tine channel and command
- other small changed
> Changes to handle qt3/qt4

- HardwareObjects/LdapLogin.py
The domain for ldap server was originally hard-coded.  In this version the default is to use the esrf domain, otherwise the domain can be set in the xml file.   No modification should be necessary to run this module at the esrf.
> LdapLogin.py adapted to work elsewhere than esrf.

- HardwareObjects/LdapLogin.py
Minor change, just to make the ou configurable (e.x., \<ldapou\>maxivusers\<\ldapou\>). In details, it's for ldapconnection.simple_bind method: if ou is defined, bind_str will be "uid=xxx,ou=xxx,dc=xx,dc=xx", otherwise it is "uid=xxx,dc=xx,dc=xx".
> For LdapLogin, make ou configurable in the xml

- __init__.py
Fix due to problem with previous name change from _logger and _formatter to hwr_logger and hwr_formatter.
> Bugfix after commit 81d135

- BaseHardwareObjects.py
- EnhancedPopen.py
- HardwareObjects/Energy.py
- HardwareObjects/InstanceServer.py
- HardwareRepository.py
- TacoDevice_MTSafe.py
Energy.py: bug fix: truth value of a hardware object can be surprising, better check with None
InstanceServer.py: bug fix: takes qt3 into account, what if QtImport doesn't exist?
HardwareRepository.py: fixed typo
TacoDevice_MTSafe.py: bug fix: reverted Python 3 change
> Various bug fixes

- BaseHardwareObjects.py
- CommandContainer.py
The Python 3 changes introduced subtle bugs one year ago.
> fixes bug introduced by Python 3 changes

- BaseHardwareObjects.py
- HardwareRepository.py
Added staticmethod to set user file directory. This directory is set at startup and could be used in hardware objects.
> 2017.03.16. Set user file directory

- BaseHardwareObjects.py
- Command/Tine.py
* Changed log info for TINE channel
> [Master] 2017.05.16 : added default value to getProperty method

- HardwareObjects/MicrodiffInOutMockup.py
- HardwareObjects/ShutterMockup.py
Hi,
- Improving Shutter- and MicrodiffInOut- Mockup
Marcus
> [2.2] - Improving Shutter- and MicrodiffInOut- Mockup

- HardwareObjects/MicrodiffInOutMockup.py
- HardwareObjects/ShutterMockup.py
Hi
- Improving Shutter- and MicrodiffInOut- Mockup
Marcus
> [master] - Improving Shutter- and MicrodiffInOut- Mockup

- HardwareObjects/XMLRPCServer.py
Author: Olof Svensson <svensson@esrf.fr>
Date:   Tue Jun 20 15:43:27 2017 +0200
Added optional "showScale" to the "save_snapshot" method.
> (code by O. Svensson, originally committed in mxcube/HardwareObjects)

- HardwareObjects/Shapes.py
- HardwareObjects/queue_entry.py
Hi,
Some smaller fixes :)
- Previous change lost in some merge sometime un_select -> de_select
- Working to implement interleaved, found small typo iterleaved -> interleaved (if not intentional ?)
- Setting correct state of Workflow QueueEntry in post_execute
Marcus
> [2.2] Minor fixes

- HardwareObjects/Shapes.py
- HardwareObjects/queue_entry.py
Hi,
Some smaller fixes :)
- Previous change lost in some merge sometime un_select -> de_select
- Working to implement interleaved, found small typo iterleaved -> interleaved (if not intentional ?)
- Setting correct state of Workflow QueueEntry in post_execute
Marcus
> [master] - Minor fixes

- HardwareObjects/queue_entry.py
Hi,
Just added some signals to be able to handle interleaved task progress.
Cheers,
Marcus
> [Master] - Added signals for interleave entry execution progress

- HardwareObjects/queue_entry.py
Hi,
Just added some signals to be able to track interleaved queue entry execution
Marcus
> [2.2] Added signals for interleaved entry execution progress

- HardwareObjects/QueueModel.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_objects_v1.py
Hey !
- Adding a easier way to reference the queue_model
- Added the possibility to set originating queue_id for nodes that was generated 
by third party software and have another origin than the node directly above it in the tree
Cheers,
Marcus
> [master] Characterization related methods

- HardwareObjects/AbstractCollect.py
- HardwareObjects/EMBL/EMBLCollect.py
- HardwareObjects/EMBL/EMBLEnergyScan.py
- HardwareObjects/EMBL/EMBLMachineInfo.py
- HardwareObjects/Transmission.py
* Moved few methods to AbstractCollect
* Added missing Transsmission hwobj
> [master] 2017.07.27. Small changes in EMBL hwobj

- HardwareObjects/ISPyBClient2.py
- HardwareObjects/queue_entry.py
Fix deprecated exception.message usage
> deperecation fix

- HardwareObjects/Shapes.py
> [master] Small update for Shapes.py

- HardwareObjects/Shapes.py
> [2.2] Small update for Shapes.py

- HardwareObjects/MD3UP.py
- HardwareObjects/Microdiff.py
- HardwareObjects/MiniDiff.py
chi is the goniometer orientation axis (0 degree means : like a MD2, -90 degrees means it's a MD3 UP).
> Handle chi angle in MiniDiff, Microdiff and new MD3UP diffractometer

- HardwareObjects/Session.py
> Session improvements

- HardwareObjects/TangoLimaVideo.py
* 'video_mode' property to be set in XML file
* fix a bug with video_live attribute to prevent server crash
* added example config. in docstring
> TangoLimaVideo.py - support for RGB24

- HardwareObjects/Energy.py
- HardwareObjects/Microdiff.py
- HardwareObjects/MiniDiff.py
- HardwareObjects/Shapes.py
- HardwareObjects/XMLRPCServer.py
See commit messages for details - do not hesitate to ask. In anyways, changes do not disturb/conflict with MXCuBE 2 operation.
> Changes to have MXCuBE 3 "mesh" feature working for 2.2

- HardwareObjects/ESRF/ID29MultiCollect.py
- HardwareObjects/Microdiff.py
- HardwareObjects/MiniDiff.py
- HardwareObjects/Shapes.py
- HardwareObjects/XMLRPCServer.py
Hi,
Smaller improvements and fixes of grid related code (mostly for MXCuBE 3)
Cheers,
Marcus
> [2.2] - Grid integration

- HardwareObjects/ESRF/ID29MultiCollect.py
- HardwareObjects/Microdiff.py
- HardwareObjects/MiniDiff.py
- HardwareObjects/Shapes.py
- HardwareObjects/XMLRPCServer.py
Hi,
Corresponding PR for Master from [2.2] - Grid int. Contains certain improvements
of the centering routines. Should not effect those using the CentringMath HO.
Cheers,
Marcus
> [MASTER] -  Grid int

- HardwareObjects/Shapes.py
Hi,
Added a method that "moves" a shape to the given motor position
Marcus
> [2.2] - Added move method to shape

- HardwareObjects/Shapes.py
Hi,
Added a method that "moves" a shape to the given motor position
Marcus
> [MASTER] - Added move method to shape

- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_objects_v1.py
automatically add diff plan to the queue, or not. Mxcube v2 should not be affected
> [2.2] Diffraction plans

- HardwareObjects/DataAnalysis.py
Adde stop method for characterisation.
I have suspicious that stoping char did not cleaned up greenlet and caused pyqt app to crash.
After adding this stop method no crashes have been observed.
> [master] 2017.09.21. Added stop method for char.

- HardwareObjects/RedisClient.py
- HardwareObjects/StateMachine.py
RedisClient - to store queue and graphics in redis
StateMachine - a try to describe GUI with states and transitions. WIP
> [master] 2017.09.21. Added missing hwobj

- HardwareObjects/GenericVideoDevice.py
Cherry-picked commit from 2.2 to detect if GenericVideoDevice is using qt or not
Fixed variable name
> [master] 2017.09.22. Cherry-pick commit from 2.2

- HardwareObjects/EdnaWorkflow.py
- HardwareObjects/XMLRPCServer.py
> Issue #76: first attempt to improve xmlrpc communication security

- HardwareObjects/ESRF/ID232MultiCollect.py
- HardwareObjects/MiniDiff.py
- HardwareObjects/Shapes.py
- HardwareObjects/detectors/LimaPilatus.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_objects_v1.py
- HardwareObjects/sample_changer/FlexHCD.py
+ forgotten commits from ID29 when we were there testing MXCuBE 3.
> Fixes from id232

- HardwareObjects/Shapes.py
Hi,
Minor fixes for the shapes object
Marcus
> [2.2] shapes fix

- HardwareObjects/Shapes.py
Hi,
Minor fixes for the shapes object
Marcus
> [master] Shapes fix

- HardwareObjects/Shapes.py
Hi, 
Handling shapes with more than one x,y screen coordinate, like lines. Previous fix that for some reason
have been lost.
Marcus
> [2.2] Shapes

- HardwareObjects/ISPyBRestClient.py
- HardwareObjects/ISPyBRestClientMockup.py
Hi,
Added the possibility to get the url to a certain data collection
Cheers
> [2.2] EXI dc_link 

- HardwareObjects/ISPyBRestClient.py
- HardwareObjects/ISPyBRestClientMockup.py
Hi,
Added the possibility to get the url to a certain data collection
Cheers
> [MASTER] EXI dc_link 

- HardwareObjects/queue_entry.py
Hi
Assigning position from centering procedure to collection.
Marcus
> [2.2] Center on collect

- HardwareObjects/queue_model_objects_v1.py
Hi,
Added possibility to get run number from path
Marcus
> [2.2] - Get run number from path

- HardwareObjects/queue_model_objects_v1.py
Hi,
Added a method to get run number and image number from a path
Marcus
> [MASTER] - Get run number from path 

- CommandContainer.py
- __init__.py
* Added subdirectories (abstract, core, etc.) to categorize Hardware objects
* If Tine or exporter channel is not attached then display error message in the gui
> [master] 2017.11.09. Small changes

- HardwareObjects/ParallelProcessing.py
- HardwareObjects/Qt4_GraphicsLib.py
- HardwareObjects/Qt4_GraphicsManager.py
- HardwareObjects/SimpleHTML.py
* New graphical features in Qt4
* Store more info about mesh scans in ISPyB
> [master] 2017.11.9. New features in Qt4 graphics

- HardwareObjects/XMLRPCServer.py
> Issue #115: added new method for centre beam

- HardwareObjects/queue_model_objects_v1.py
Hi,
Added method for setting sample data from dict
Marcus
> [2.2] Added method for setting sample data from dict

- HardwareObjects/queue_model_objects_v1.py
HI,
Added method for setting sample data from dict
Marcus
> [MASTER] - Added method for setting sample data from dict

- HardwareObjects/BeamlineTools.py
- HardwareObjects/ISPyBClient2.py
- HardwareObjects/MicrodiffMotor.py
- HardwareObjects/StateMachine.py
- HardwareObjects/UnitTest.py
- HardwareObjects/XMLRPCServer.py
- tests/xml/mini-diff-mockup.xml
* HardwareObjects/BeamlineTools.py: hwobj adds method calls in the top menu of main gui. Added possibility to add icon, confirmation dialog when method requested. Also added option to enable method in the expert mode.
* HardwareObjects/ISPyBClient2.py: added method `get_dc_display_link`. Returns link to ispyb gui with selected data collection id. User can open data collection window from mxcube. Store robot action (load/unload) in ISPyB
* HardwareObjects/MicrodiffMotor.py: fixed relative move. Added `get_max_speed` method
* HardwareObjects/StateMachine.py: clean up
* HardwareObjects/UnitTest.py:
* HardwareObjects/XMLRPCServer.py: added method `add_processing_message` to collect processing messages from EDNA and
* tests/xml/mini-diff-mockup.xml: added more info
> [master] 2017.11.10. Hwobj dev

- HardwareObjects/RedisClient.py
Added try around the connection to flux hwobj
> [master] 2017.11.10. Fix for redis hwobj

- HardwareObjects/AbstractEnergyScan.py
- HardwareObjects/XMLRPCServer.py
* Fixed bug in XMLRPCServer
* Added missing methods in AbstractEnergyServer
> [master] 2017.11.20 Fixed two bugs

- HardwareObjects/EdnaWorkflow.py
Hello,
Supporting multiple require arguments 
Marcus
> [2.2] - Supporting multiple require arguments

- HardwareObjects/queue_entry.py
Hi,
Emitting signal when energy scan is done, more generic than the signal emitted by doChooch of the EnergyScan HW.
Marcus
> [2.2] Added energy scan finished signal

- HardwareObjects/queue_entry.py
Hi,
Just removed unused argument from signal,
Marcus
> [2.2] diff plan

- HardwareObjects/AbstractCollect.py
- HardwareObjects/CollectMockup.py
- HardwareObjects/DiffractometerMockup.py
- HardwareObjects/FluxMockup.py
- HardwareObjects/sample_changer/PlateManipulatorMockup.py
* HardwareObjects/AbstractCollect.py: emit progressInit signal in abstractCollect and not in Mockup
* HardwareObjects/CollectMockup.py
* HardwareObjects/DiffractometerMockup.py: added set_phase and fixed centering
* new FluxMockup and PlateManipulatorMockup
> [master] Small fixes for abstrac and mockup

- HardwareObjects/AbstractCollect.py
- HardwareObjects/AbstractDetector.py
- HardwareObjects/EMBL/EMBLDetector.py
- HardwareObjects/GenericDiffractometer.py
- HardwareObjects/ISPyBClient2Mockup.py
- HardwareObjects/SOLEIL/PX2queue_entry.py
- HardwareObjects/SampleChangerMockup.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_objects_v1.py
- HardwareRepository.py
Part of series: 1 - merging the GPhL Workflow/emulation branch into master
This PR contains bug fixes in existing code, and additional features (small) that should not break anything (hopefully)
> GPhL Fixes and additions

- HardwareObjects/AbstractDetector.py
- HardwareObjects/CollectMockup.py
- HardwareObjects/DetectorMockup.py
- HardwareObjects/DiffractometerMockup.py
- HardwareObjects/EnergyMockup.py
- HardwareObjects/GenericDiffractometer.py
- HardwareObjects/MotorMockup.py
- HardwareObjects/ResolutionMockup.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_objects_v1.py
Part of series: 2 - merging the GPhL Workflow/emulation branch into master
This PR contains a couple of refactorings (mainly to do with motor position handling by collection and sample centring), that change existing behaviour, and upgrades to Mockup objects.
> Mockup changes and refactoring

- HardwareObjects/GenericVideoDevice.py
- HardwareObjects/Qt4_GraphicsLib.py
- HardwareObjects/Qt4_GraphicsManager.py
- HardwareObjects/Qt4_LimaVideo.py
- HardwareObjects/Qt4_VimbaVideo.py
* Fixed grid layouts
* Added new hwobj Qt4_VimbaVideo. Alternative to obtain frames from prosilica camera. Works without sudo!
> [master] Small fixes for qt4 graphics

- HardwareObjects/AbstractMultiCollect.py
- HardwareObjects/ESRF/ESRFMultiCollect.py
- HardwareObjects/ESRF/ID29MultiCollect.py
- HardwareObjects/ESRF/ID29XRFSpectrum.py
- HardwareObjects/ISPyBClient2.py
- HardwareObjects/ISPyBRestClient.py
- HardwareObjects/Microdiff.py
- HardwareObjects/Session.py
- HardwareObjects/XRFSpectrum.py
Hi,
Fixes for the XRF scan, snapshots and ISPyBClient2 (mostly made by Antonia who are on vacation for the moment)
Marcus
> [2.2] XRF Fixes and some minor bug fixes

- BaseHardwareObjects.py
- HardwareObjects/AbstractMotor.py
- HardwareObjects/EnergyMockup.py
> [master] Added deprecation warnings

- HardwareObjects/ISPyBClient2.py
- HardwareObjects/ISPyBClient2Mockup.py
> Add an echo method to the ISPyBClient.

- HardwareObjects/AbstractMotor.py
- HardwareObjects/CollectEmulator.py
- HardwareObjects/DiffractometerMockup.py
- HardwareObjects/GphlWorkflow.py
- HardwareObjects/GphlWorkflowConnection.py
- HardwareObjects/MotorMockup.py
- HardwareObjects/Qt4_GraphicsManager.py
- HardwareObjects/ResolutionMockup.py
Bug fixes necessary to have mock data collection work, including mock centring:
- AbstractMotor: Added syncMove(Relative) functions (wrappers)
- CollectEmulator - cleanup
- DiffractometerMockup: Add 90deg rotation during centring, remove centringDone
- GphlWorkflowConnection: Translation message bug fix
- MotorMockup bug fix (added timeout parameter)
- Qt4_GraphicsManager: three-click centring bug fix
- ResolutionMockup bug fix
> Bug fixes (centring etc.), GPhL code

- HardwareObjects/BeamlineSetup.py
> revert min,max for exp time limits

- HardwareObjects/AbstractCollect.py
* Added missing error handling if the collection fails
* Added try for reading plate position
> Abstract collect bug

- HardwareObjects/BeamlineSetup.py
- HardwareObjects/ESRF/ID29XRFSpectrum.py
- HardwareObjects/Energy.py
- HardwareObjects/ISPyBClient2.py
- HardwareObjects/Microdiff.py
- HardwareObjects/XRFSpectrum.py
- HardwareObjects/sample_centring.py
- HardwareRepository.py
Includes all differences between Hardware Repository in MXCuBE 2 and MXCuBE 3 on ID29
> Latest code from ESRF ID29, mxcube 2 + mxcube 3

- HardwareObjects/Qt4_GraphicsLib.py
- HardwareObjects/Qt4_GraphicsManager.py
Bugfix:
* Added possibility to cancel manual beam positioning with ESC key.
* Added check for nan values to avoid error in redrawing.
New feature
* Added histograms.
* Added coordinate map for grids to speed up redrawing.
> [master] Qt4 graphics: bugfix and new feature

- HardwareObjects/AbstractCollect.py
- HardwareObjects/CollectEmulator.py
- HardwareObjects/GphlWorkflow.py
- HardwareObjects/GphlWorkflowConnection.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_enumerables_v1.py
- HardwareObjects/queue_model_objects_v1.py
Upgrade and bug fixes for GPhL code - minor tweaks only to non-GPhL code
> GPhL code upgrade

- HardwareObjects/BlissActuator.py
- HardwareObjects/BlissInOut.py
- HardwareObjects/ESRF/BeamCmds.py
- HardwareObjects/ESRF/ID232BeamCmds.py
- HardwareObjects/ESRF/ID29BeamCmds.py
- HardwareObjects/Scintillator.py
Hi,
Added a class to be able to handle HardwareObject Actuators as beamline actions. Small side note, this has nothing to do with the UI-API discussion (which I imagine it can seem like)
Marcus
> 2.2 HardwareObject Actuator as beamline action

- HardwareObjects/CollectEmulator.py
Homogenised getting of gphl hardware objects, to fix a bug when GPhL code is not installed
> Bug fix: handling of missing GPhL installation, and gphl config bug

- HardwareObjects/GenericDiffractometer.py
Solves #169 and mxcube/mxcube#229
> [master] GenericDiffractometer fix

- HardwareObjects/BlissActuator.py
- HardwareObjects/ESRF/BeamCmds.py
- HardwareObjects/ESRF/ID29BeamCmds.py
- HardwareObjects/MD2Motor.py
- HardwareObjects/Microdiff.py
- HardwareObjects/MicrodiffAperture.py
- HardwareObjects/MicrodiffHutchTrigger.py
- HardwareObjects/MiniDiff.py
- HardwareObjects/sample_changer/FlexHCD.py
Hi,
Some small updates to:
- FlexHCD sample changer code, state is now reported more often
- Beamline actions, added some ID29 specific actions
- Hutchtrigger, now more self contained, we do not need a brick to trigger it ...
- Other bug fixes
Marcus
> Minor updates

- HardwareObjects/GenericDiffractometer.py
- HardwareObjects/MAXIV/BIOMAXMD3.py
- HardwareObjects/Qt4_TangoLimaVideo.py
- HardwareObjects/Session.py
- HardwareObjects/queue_model_objects_v1.py
-- Fixing a few typos
-- add getHeight() and getWidth() to Qt4_TangoLimaVideo
-- seems weird that session_hwobj should be called from within Session class ...
-- making sure data_model.precision is transformed into str before concatenating with other strings
> Various small improvements

- HardwareObjects/BeamInfoMockup.py
- HardwareObjects/DiffractometerMockup.py
- HardwareObjects/MachineInfoMockup.py
- HardwareObjects/SampleChangerMockup.py
-- Change the omega axis orientation so that it corresponds to the orientation of sample on the simulated image
-- Make simulated min and max current configurable
-- Make number of baskets and samples in basket configurable
> Improving mockups

- HardwareObjects/GenericDiffractometer.py
- HardwareObjects/GphlWorkflow.py
- HardwareObjects/ISPyBClient2.py
Bug fixes and cleanup of exception handling.
Also a few GPhL-only lfixes in other files.
NB logger.exception() automatically prints the trace of the last exeption. You should not also pass it as a message, lest it gets printed twice
> ISPyBCient2 bug fixes

- HardwareObjects/BeamlineActionsMockup.py
Hi,
Fixed indentation mistake
Marcus
> Fixed indentation mistake

- BaseHardwareObjects.py
Instead of always using logging.getLogger()... use self.print_log(type, level, msg)
> [master] Added print_log method

- HardwareObjects/GphlWorkflowConnection.py
- tests/xml/session.xml
GPhL bug fix. session.xml changed default base directory names to fit new GPhL dockers
> GPhL bug fix and change to session.xml

- HardwareObjects/ISPyBRestClient.py
Hi 
Improved get_dc WS call, added function to get full size diffraction image
Cheers,
Marcus
> [2.2] Improved WS calls

- HardwareObjects/ESRF/BlissHutchTrigger.py
- HardwareObjects/ESRF/ESRFBeamInfo.py
- HardwareObjects/ESRF/ID30BBeamCmds.py
Hutch trigger and  Beam info ESRF specific.
> Esrf bliss

- CommandContainer.py
- HardwareObjects/ESRF/BeamCmds.py
- HardwareObjects/Shapes.py
Hi,
- Added a new shape type for points that are only centered in the plane
- Small fix to CommandContainer to avoid adding the same argument twice
Marcus
> BeamCmds and Shapes

- HardwareObjects/CollectEmulator.py
- HardwareObjects/GphlWorkflow.py
- HardwareObjects/GphlWorkflowConnection.py
- HardwareObjects/queue_model_objects_v1.py
Code changes are relevant for Global Phasing code only.
> GPhL code update

- HardwareObjects/GenericVideoDevice.py
- HardwareObjects/Qt4_GraphicsLib.py
- HardwareObjects/Qt4_GraphicsManager.py
- HardwareObjects/Qt4_VimbaVideo.py
- HardwareObjects/VaporyVideo.py
Some bug fixes and new features
> [master] Qt graphics

- HardwareObjects/QueueManager.py
- HardwareObjects/QueueModel.py
- HardwareObjects/Session.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_enumerables_v1.py
- HardwareObjects/queue_model_objects_v1.py
Last PR from the PR series to update the queue and queue_model
> [master] Queue and queue model

- Command/Tine.py
- CommandContainer.py
- HardwareObjects/Attenuators.py
- HardwareObjects/BeamlineSetup.py
- HardwareObjects/CentringMath.py
- HardwareObjects/DataAnalysis.py
- HardwareObjects/ExporterMotor.py
- HardwareObjects/MiniKappaCorrection.py
- HardwareObjects/XMLRPCServer.py
- HardwareObjects/sample_changer/PlateManipulator.py
- HardwareRepository.py
* Command/Tine.py: added variable force to the getValue method to force value reading
* CommandContainer.py: likewise
* HardwareObjects/Attenuators.py: cleaned up
* HardwareObjects/BeamlineSetup.py: added advance methods to queue_model_objects.DataCollection. This is needed to display processing messages
* HardwareObjects/CentringMath.py. getPosition -> get_position
* HardwareObjects/DataAnalysis.py: fixed log message
* HardwareObjects/ExporterMotor.py
* HardwareObjects/MiniKappaCorrection.py
* HardwareObjects/XMLRPCServer.py: added methods to handel processing results
* HardwareObjects/sample_changer/PlateManipulator.py
* HardwareRepository.py: code cleanup
> [master] Various fixes

- CommandContainer.py
- HardwareObjects/ESRF/BeamCmds.py
- HardwareObjects/ESRF/ID29BeamCmds.py
- HardwareObjects/ISPyBRestClient.py
- HardwareObjects/SampleChangerMockup.py
- HardwareObjects/Shapes.py
- HardwareObjects/XMLRPCServer.py
- HardwareObjects/queue_model_objects_v1.py
- HardwareObjects/sample_changer/FlexHCD.py
- HardwareObjects/sample_changer/GenericSampleChanger.py
Hi,
Some fixes to FlexHCD, Shapes (for MXCuBE3) and ISPyBRestClient
- Improved the sample loading and unloading routines of FlexHCD
- Hiding grids that get out of a certain, configurable,  threshold angle automatically when omega rotates
- Handling workfloStepId's in get_dc of ISPyBRestClient
- And some other minor fixes like typos
Marcus
> [2.2] Shapes and SC

- HardwareObjects/sample_changer/FlexHCD.py
Add the control of the sample changer using the exporter protocol.
Improve the load/unload handle for faster execution.
> Flex HCD with exporter

- HardwareObjects/ESRF/ID232BeamCmds.py
- HardwareObjects/ESRF/ID232BeamDefiner.py
- HardwareObjects/ESRF/ID232HutchTrigger.py
- HardwareObjects/ESRF/ID232MultiCollect.py
Hi,
Some ID232 specific HardwareObjects
Marcus
> ID232 specific

- HardwareObjects/MD3UP.py
- HardwareObjects/MiniDiff.py
Hi,
Added MD3UP centring code and move to beam using sampx and sampy for MiniDiff
Marcus
> Added MD3UP centring code

- HardwareObjects/AbstractAttenuators.py
- HardwareObjects/Attenuators.py
Changed signal name trslimitsChanged -> limitsChanged
We should agree on a generic naming.
* valueChanged
* stateChanged
* limitsChanged
> [master] Attenuators

- HardwareObjects/AbstractCollect.py
- HardwareObjects/CollectMockup.py
- HardwareObjects/DiffractometerMockup.py
- HardwareObjects/EMBL/EMBLCollect.py
- HardwareObjects/SOLEIL/PX2/PX2Collect.py
* Moved method update_lims_with_workflow from Mockup to Abstract (used in all inherited classes)
* Small fixes to DiffractometerMockup
> [master] Small additions to abstract classes

- HardwareObjects/EnergyMockup.py
- HardwareObjects/TransmissionMockup.py
Hi,
The set method on TransmissionMockup and startMoveEnergy on EnergyMockup have for some
reason gone missing, so I added them back.
Regards,
Marcus
> [2.2] Minor fixes to Energy and Transmission mockups

- HardwareObjects/ESRF/BlissHutchTrigger.py
- HardwareObjects/ESRF/ID232PhotonFlux.py
- HardwareObjects/ESRF/TangoKeithleyPhotonFlux.py
- HardwareObjects/ESRF/Transmission.py
- HardwareObjects/Energy.py
- HardwareObjects/MachCurrent.py
- HardwareObjects/Microdiff.py
- HardwareObjects/MicrodiffInOut.py
Hi,
Minor fixes to Energy, Microdiff, MachCurrent and ESRF specific HO's.
Regards,
Marcus
> [2.2] Minor Energy, Microdiff and ESRF specific updates

- HardwareObjects/ESRF/BlissRontecMCA.py
- HardwareObjects/sample_changer/FlexHCD.py
Change BlissRontecMCA to use the bliss object. Cosmetic cleanup of FlexHCD.
> Rontec fix

- HardwareObjects/ALBA/ALBAAutoProcessing.py
- HardwareObjects/ALBA/ALBABackLight.py
- HardwareObjects/ALBA/ALBABeamInfo.py
- HardwareObjects/ALBA/ALBACats.py
- HardwareObjects/ALBA/ALBACatsMaint.py
- HardwareObjects/ALBA/ALBAClusterJob.py
- HardwareObjects/ALBA/ALBACollect.py
- HardwareObjects/ALBA/ALBADataAnalysis.py
- HardwareObjects/ALBA/ALBAEnergy.py
- HardwareObjects/ALBA/ALBAEpsActuator.py
- HardwareObjects/ALBA/ALBAFastShutter.py
- HardwareObjects/ALBA/ALBAFlux.py
- HardwareObjects/ALBA/ALBAFrontEnd.py
- HardwareObjects/ALBA/ALBAISPyBClient.py
- HardwareObjects/ALBA/ALBAMachineInfo.py
- HardwareObjects/ALBA/ALBAMiniDiff.py
- HardwareObjects/ALBA/ALBAPilatus.py
- HardwareObjects/ALBA/ALBASession.py
- HardwareObjects/ALBA/ALBASupervisor.py
- HardwareObjects/ALBA/ALBAZoomMotor.py
Massive changes for ALBA-specific HwObjs.
> Alba specific changes

- HardwareObjects/MAXIV/BIOMAXBeamlineActions.py
- HardwareObjects/MAXIV/BIOMAXCollect.py
- HardwareObjects/MAXIV/BIOMAXEiger.py
- HardwareObjects/MAXIV/BIOMAXMD3.py
- HardwareObjects/MAXIV/BIOMAXPatches.py
- HardwareObjects/MAXIV/MaxIVSession.py
> MAXIV updates

- HardwareObjects/sample_changer/Cats90.py
- HardwareObjects/sample_changer/CatsMaint.py
Some small additions to the cats. 
WIP because it is probably a mess to merge these ones in 2.2 instead of directly into master, but all my code is based in 2.2 arghh...
@jordiandreu, maybe I can push this commits to your PR? Or you cherry pick? If you think are useful of course
> Cats changes

- HardwareObjects/ISPyBClient2.py
- HardwareObjects/MAXIV/BIOMAXPatches.py
ISPyBClient2.py 
-- remove trailing parenthesis
-- fix wrong indent
BIOMaxPatches.py
-- probably forgotten finally clause (finally can not come before else)
> Fixes to ISPyBClient2.py and BIOMaxPatches.py

- HardwareObjects/CollectEmulator.py
- HardwareObjects/Session.py
This hack should never have been in Session in the first place. It is now moved to CollectEmulator
> Replaced override_directories hack with CollectEmulator implementation

- HardwareObjects/ISPyBClient2.py
Hi 
Noticed that we need to be able to specify if we want the LIMS login routine to create a session or not.
The first commit contains the actual functionality while the last one is PEP-8 formatting. I will make a separate PR for this to master at a later stage, depending on what you think of this functionality ofcourse.
Marcus
> [2.2] Option to create LIMS session

- HardwareObjects/ISPyBClient2Mockup.py
Hi 
- Added create_session parameter to login method
- Changed "proposal number" to 0, the "propopsal number" is sometimes treated as a
number and 000 are thus naturally truncated to 0
Regards
Marcus
> [2.2] LIMS Mockup fixes

- HardwareObjects/Session.py
@beteva My apologies. Good to get rid of the junk. Hopefully this is the last in this series?
> Yet more cleanup of parameter-override set-up

- HardwareObjects/ALBA/ALBAISPyBClient.py
- HardwareObjects/ISPyBClient.py
- HardwareObjects/SOLEIL/SOLEILISPyBClient.py
- HardwareObjects/mockup/ISPyBClientMockup.py
> Renamed ISPyBClient2 to ISPyBClient

- test/test_example.py
Hi,
Just added dummy test file to make pytest return with exit code 0, just until I've added a first example test.
Marcus
> Added dummy test to make pytest happy

- HardwareObjects/BlissActuator.py
This should be the last 'from x import *' involving AbstractActuator.
> Cleaned up 'from x import *' import

- COPYING
> Preparing for LGPL3

- BaseHardwareObjects.py
- CommandContainer.py
- HardwareObjects/RobodiffFShut.py
- HardwareObjects/queue_entry.py
- HardwareRepository.py
> Refactored some 'from ... import *' and cleaned up imports

- Command/Exporter.py
- CommandContainer.py
- HardwareObjects/ESRF/ID29XRFSpectrum.py
- HardwareObjects/MD2Motor.py
- HardwareObjects/abstract/AbstractMotor.py
Change some methods from CamelCase to snake_case. Deprecation warnings.
> Some CamelCase cleanup

- HardwareObjects/EMBL/EMBLSession.py
- HardwareObjects/Session.py
* Fixed archive path.
* Commented two not used variables
* new EMBLSession.py
> Fixed Session hwobj

- HardwareObjects/EMBL/EMBLParallelProcessing.py
- HardwareObjects/GenericParallelProcessing.py
- HardwareObjects/ISPyBClient.py
- HardwareObjects/SimpleHTML.py
- HardwareObjects/XMLRPCServer.py
- HardwareObjects/mockup/ParallelProcessingMockup.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_enumerables.py
- HardwareObjects/queue_model_objects.py
* Small fixes for XMLRPC : by defaults set all interfaces to false:
* Cleaned up GenericParallelProcessing. Soon will be renamed to AbstractParallelProcessing
* Added two new experiment types: still (for serial mx) and imaging (xray tomography).
* Added missing methods
> Added new collection items to handle ssx and imaging dc

- Command/Mockup.py
- CommandContainer.py
Added mockup channel and command to test the channel and command interface
> Mockup channel and command

- HardwareObjects/BeamlineSetup.py
- HardwareObjects/DozorParallelProcessing.py
- HardwareObjects/EMBL/EMBLBeamlineTest.py
- HardwareObjects/EMBL/EMBLCollect.py
- HardwareObjects/EMBL/EMBLEnergy.py
- HardwareObjects/EMBL/EMBLFlux.py
- HardwareObjects/EMBL/EMBLSafetyShutter.py
- HardwareObjects/EMBL/EMBLXrayImaging.py
- HardwareObjects/GenericParallelProcessing.py
- HardwareObjects/ISPyBRestClient.py
- HardwareObjects/InstanceServer.py
- HardwareObjects/Qt4_GraphicsLib.py
- HardwareObjects/Qt4_GraphicsManager.py
- HardwareObjects/QueueModel.py
- HardwareObjects/autoprocessing.py
- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_objects.py
- configuration/xml-qt/beamline-setup.xml
Some adjustments after a major mxcube qt refactoring (see https://github.com/mxcube/mxcube/pull/310)
> Adjustments after refactoring of mxcube qt

- HardwareObjects/EdnaWorkflow.py
- HardwareObjects/ISPyBClient.py
- HardwareObjects/ISPyBRestClient.py
- HardwareObjects/TangoShutter.py
- HardwareObjects/mockup/CatsMaintMockup.py
- HardwareObjects/mockup/ISPyBClientMockup.py
- HardwareObjects/mockup/ISPyBRestClientMockup.py
- HardwareObjects/mockup/MDCameraMockup.py
- HardwareObjects/mockup/MachInfoMockup.py
- HardwareObjects/mockup/MicrodiffInOutMockup.py
- HardwareObjects/mockup/PlottingMockup.py
- HardwareObjects/mockup/XRFMockup.py
Hi,
A few more fixes for running the code under Python 3, especially for getting the MXCubE3 mockups to run again. Some functionality, the create_session parameter, of the ISPyBClients that have fallen away during the work so I added it back again.
I managed to get the mockups run in both Python 2.7 and Python 3, quite limited in Python3 for the moment but it runs.
Marcus
> Additional Python 3 fixes

- HardwareObjects/ESRF/BM14MultiCollect.py
- HardwareObjects/ESRF/ESRFEnergyScan.py
- HardwareObjects/ESRF/ESRFMultiCollect.py
- HardwareObjects/ESRF/ID232MultiCollect.py
- HardwareObjects/ESRF/ID29MultiCollect.py
- HardwareObjects/ESRF/ID30A3MultiCollect.py
- HardwareObjects/ESRF/ID30BMultiCollect.py
- HardwareObjects/ESRF/ID30BXRFSpectrum.py
- HardwareObjects/ESRF/Oxford700.py
- HardwareObjects/ESRF/TangoKeithleyPhotonFlux.py
Hi,
Just removed some unused variables
Marcus
> [ESRF-HO] Removed unused variables

- HardwareObjects/BeamlineSetup.py
- HardwareObjects/GenericDiffractometer.py
- HardwareObjects/Shapes.py
- HardwareObjects/abstract/AbstractDetector.py
- HardwareObjects/mockup/DiffractometerMockup.py
- HardwareObjects/mockup/SampleChangerMockup.py
- HardwareObjects/queue_entry.py
Dear all,
Some adaptations needed after the API changes we have introduced recently, along with some code cleanup.
For Qt developers pay attention to:
snapshot = self.shape_history.get_scene_snapshot()
to
snapshot = self.shape_history.get_snapshot()
Marcus
> Adaptations needed after API changes

- .pylintrc
- .travis.yml
- Command/Tine.py
- HardwareObjects/EMBL/EMBLAperture.py
- HardwareObjects/EMBL/EMBLAutoProcessing.py
- HardwareObjects/EMBL/EMBLBSD.py
- HardwareObjects/EMBL/EMBLBeamFocusing.py
- HardwareObjects/EMBL/EMBLBeamInfo.py
- HardwareObjects/EMBL/EMBLBeamlineTest.py
- HardwareObjects/EMBL/EMBLCRL.py
- HardwareObjects/EMBL/EMBLCollect.py
- HardwareObjects/EMBL/EMBLDetector.py
- HardwareObjects/EMBL/EMBLEnergyScan.py
- HardwareObjects/EMBL/EMBLFlux.py
- HardwareObjects/EMBL/EMBLImageTracking.py
- HardwareObjects/EMBL/EMBLMachineInfo.py
- HardwareObjects/EMBL/EMBLMiniDiff.py
- HardwareObjects/EMBL/EMBLMotorsGroup.py
- HardwareObjects/EMBL/EMBLPPUControl.py
- HardwareObjects/EMBL/EMBLParallelProcessing.py
- HardwareObjects/EMBL/EMBLSession.py
- HardwareObjects/EMBL/EMBLSlitBox.py
- HardwareObjects/EMBL/EMBLTableMotor.py
- HardwareObjects/EMBL/EMBLXRFSpectrum.py
- HardwareObjects/EMBL/EMBLXrayImaging.py
- HardwareObjects/EMBL/TINEMotor.py
- HardwareObjects/Marvin.py
* Updated EMBL hardware objects
> Update of EMBL hardware objects

- HardwareObjects/queue_entry.py
- HardwareObjects/queue_model_objects.py
* Added missing parameters required by the gui
* added execution of the xrayimaging queue entry
> Added missing XrayImaging parameters

- HardwareObjects/mockup/QtVideoMockup.py
The missing bug fix recently discussed
> Added missing import in QtVideoMockup

- HardwareObjects/abstract/AbstractCollect.py
Needs merging *before* new 'release' is made
> Simple bug fix

- HardwareObjects/ISPyBClient.py
Add the decode method necessary to convert
the data object to be uploaded to ISPyB.
This method is used in the create_session method.
> Add missing decode method (issue 371)

- .pylintrc
- .travis.yml
- HardwareObjects/abstract/AbstractNState.py
- HardwareObjects/mockup/BeamlineTestMockup.py
- HardwareObjects/mockup/CameraMockup.py
- HardwareObjects/mockup/CatsMaintMockup.py
- HardwareObjects/mockup/CollectMockup.py
- HardwareObjects/mockup/DataAnalysisMockup.py
- HardwareObjects/mockup/DiffractometerMockup.py
- HardwareObjects/mockup/FluxMockup.py
- HardwareObjects/mockup/ISPyBClientMockup.py
- HardwareObjects/mockup/LimaDetectorMockup.py
- HardwareObjects/mockup/MachineInfoMockup.py
- HardwareObjects/mockup/MockupActuator.py
- HardwareObjects/mockup/Oxford700Mockup.py
- HardwareObjects/mockup/ParallelProcessingMockup.py
- HardwareObjects/mockup/PlateManipulatorMockup.py
- HardwareObjects/mockup/ResolutionMockup.py
- HardwareObjects/mockup/SOLEILDataAnalysisMockup.py
- HardwareObjects/mockup/ShapeHistoryMockup.py
- HardwareObjects/mockup/ShutterMockup.py
- HardwareObjects/mockup/TransmissionMockup.py
- test/pytest/test_shutter.py
* Added missing imports.
* Fixed import to use absolute imports.
* Removed duplicated methods (for example in the ISPyBClientMockup)
* Fixed PlateManipulatorMockup
* Enable pylint check for mockup directory
* Rewrote MachineInfoMockup to use OrderedDict
* Solved #363 
I could not sort out Oxford700Mockup.py and LimaDetectorMockup.py (unable to import PyTango). So for time beeing I disabled pylint check for these two files.
> Enabled pylint check for mockup objects

- BaseHardwareObjects.py
- ConvertUtils.py
- HardwareObjects/BeamlineSetup.py
- HardwareObjects/DESY/MjpgStreamVideo.py
- HardwareObjects/DESY/NanoDiff.py
- HardwareObjects/EMBL/EMBLBeamlineTest.py
- HardwareObjects/ESRF/ESRFMetadataManagerClient.py
- HardwareObjects/ESRF/ESRFMultiCollect.py
- HardwareObjects/GphlMessages.py
- HardwareObjects/GphlWorkflow.py
- HardwareObjects/ISPyBClient.py
- HardwareObjects/MAXIV/old/MAXLABMultiCollect.py
- HardwareObjects/QtGraphicsLib.py
- HardwareObjects/abstract/AbstractCollect.py
- HardwareObjects/mockup/CollectEmulator.py
- HardwareRepository.py
- configuration/gphl_mock/mxcollect.xml
Also some minor fixes, and fixes to global phasing code
> Added Python 2/3-compatible string type checking

- HardwareObjects/GphlWorkflow.py
- HardwareObjects/GphlWorkflowConnection.py
- HardwareObjects/SOLEIL/PX1/PX1Pilatus.py
- HardwareObjects/mockup/CollectEmulator.py
- configuration/embl_hh_p14/gphl-setup.xml
- configuration/embl_hh_p14/gphl-workflow.xml
- configuration/gphl_mock/gphl-setup.xml
- requirements_python2.txt
- requirements_python3.txt
Added parameter validation to GPhL using paramsgui for runtime parameter queries. 
NB goes with matching PR in mxcube
> Added parameter validation for GPhL parameter queries

- HardwareObjects/abstract/AbstractEnergy.py
Hi
- Small improvement of EnergyMockup is_ready
Marcus
> EnergyMockup is_ready

- HardwareObjects/queue_model_objects.py
Added missing attribute. After merging this PR I will create a PR in mxcube with submodule update to fix the bug.
> Bugfix for mxcube issue 352

- HardwareObjects/abstract/AbstractProcedure.py
> AbstractProcedure

- HardwareObjects/Beamline.py
- HardwareObjects/DataAnalysis.py
- HardwareObjects/GenericDiffractometer.py
- HardwareObjects/mockup/ISPyBClientMockup.py
- HardwareObjects/mockup/MDCameraMockup.py
Hi,
A few changes needed to get MXCuBE3 mockups to run with the latest Python3 and Hardware Repository work.
Cheers,
Marcus
> Minor updates for MXCuBE3 mock

- HardwareObjects/mockup/DetectorMockup.py
Hi all,
Removed inheritance from HardwareObject in DetectorMockup since AbstractDetector is now inherting HardwareObject instead.
Cheers,
Marcus
> DetectorMockup - Minor fix

- Command/Exporter.py
- Command/embl/ExporterClient.py
- Command/embl/MDClient.py
- Command/embl/StandardClient.py
Camel to snake case refactoring. Linting. Python3 compatibility.
> Exporter refactoring

- HardwareObjects/FlexHCD.py
> camel to snake case

- HardwareObjects/AxisCamera.py
- HardwareObjects/EMBL/EMBLAperture.py
- HardwareObjects/EMBL/EMBLBSD.py
- HardwareObjects/EMBL/EMBLBeamCentering.py
- HardwareObjects/EMBL/EMBLBeamInfo.py
- HardwareObjects/EMBL/EMBLBeamlineTest.py
- HardwareObjects/EMBL/EMBLBeamstop.py
- HardwareObjects/EMBL/EMBLCRL.py
- HardwareObjects/EMBL/EMBLCollect.py
- HardwareObjects/EMBL/EMBLDetector.py
- HardwareObjects/EMBL/EMBLFlux.py
- HardwareObjects/EMBL/EMBLImageTracking.py
- HardwareObjects/EMBL/EMBLMachineInfo.py
- HardwareObjects/EMBL/EMBLMiniDiff.py
- HardwareObjects/EMBL/EMBLMotorsGroup.py
- HardwareObjects/EMBL/EMBLOfflineProcessing.py
- HardwareObjects/EMBL/EMBLOnlineProcessing.py
- HardwareObjects/EMBL/EMBLPPUControl.py
- HardwareObjects/EMBL/EMBLQueueEntry.py
- HardwareObjects/EMBL/EMBLResolution.py
- HardwareObjects/EMBL/EMBLSSXChip.py
- HardwareObjects/EMBL/EMBLSafetyShutter.py
- HardwareObjects/EMBL/EMBLSession.py
- HardwareObjects/EMBL/EMBLTransfocator.py
- HardwareObjects/EMBL/EMBLTransmission.py
- HardwareObjects/EMBL/EMBLXRFSpectrum.py
- HardwareObjects/EMBL/EMBLXrayImaging.py
- HardwareObjects/Marvin.py
- HardwareObjects/QtAxisCamera.py
* Adjustments to new HWR.beamline
* New hwobj to access AxisCamera
> EMBL hwobj update

- HardwareObjects/BlissMotor.py
- HardwareObjects/ExporterMotor.py
- HardwareObjects/FlexHCD.py
- HardwareObjects/Resolution.py
- HardwareObjects/abstract/AbstractMotor.py
AbstarctMotor cleanup. MotorStates is Enum.
Change BlissMotor, ExporterMotor, Resolution to correspond to the new AbstractMotor.
> [WIP] Motors

- HardwareObjects/BlissMotor.py
- HardwareObjects/ExporterMotor.py
- HardwareObjects/Resolution.py
- HardwareObjects/abstract/AbstractDetector.py
- HardwareObjects/abstract/AbstractMotor.py
> AbstractDetector new attributes and methods

- BaseHardwareObjects.py
Proposed new HardwareObject class(es) as discussed. I have, of necessity, also done a bit of cleanup on the related abstract classes.
NB, The HardwareObjectMixin is unfortunately necesary. We cannot merge it with anything else because
1) the functionality now in HardwareObject is specific to the xml implementation.
2) The yaml implementation is also used for things that are not HardwareObjects (like Beamline)
For clarification, ConfiguredObject is the equivalent of HardwareObjectNode.
> WIP: Updated HardwareObject and related classes as discussed by developers.

- BaseHardwareObjects.py
- HardwareObjects/abstract/AbstractActuator.py
- HardwareObjects/abstract/AbstractMotor.py
Dear all,
this is the proposed implementation for the new abstract actuator as decided at the last MXCuBE developers' meeting. Feel free to use it ;-)
Marcus and Antonia
> Abstract actuator

- HardwareObjects/TangoLimaVideo.py
- HardwareObjects/TangoLimaVideoLoopback.py
Hi
Added TangoLimaVideoLoopback that writes the from the camera to a loopback device and starts a process that processes the stream, i.e converting it to MPEG
Marcus
> Added TangoLimaVideoLoopback

- HardwareObjects/abstract/AbstractBeam.py
Dear all,
I forgot to add the AbstractBeam that Antonia started to work on, this will probably create some conflicts with @IvarsKarpics latest PR #442, it would be good if we could merge these two.
Cheers,
Marcus
> Added previously missing file AbstractBeam

- HardwareObjects/mockup/MotorMockup.py
- configuration/test/detector-distance-mockup.xml
This fixes the pytest for the detector HardwareObject.
> Fix detector test

- HardwareObjects/abstract/AbstractBeam.py
- HardwareObjects/mockup/BeamInfoMockup.py
- HardwareObjects/mockup/EDNACharacterisationMockup.py
- HardwareObjects/mockup/EnergyMockup.py
- HardwareObjects/mockup/MDCameraMockup.py
- HardwareObjects/mockup/MicrodiffZoomMockup.py
- HardwareObjects/mockup/MotorMockup.py
Dear all,
Here are a few updates to some of the mockup objects, its just the minimal changes inorder to get the mockup version to work with the new HWR API. The idea is to complete this work during our next code camp. But, of course, let me know if there is anything that you would like to address immediately and we will sort it out, only less work for later :).
Cheers,
Marcus
> Adapted some mockups to new HWR API

- HardwareObjects/BlissMotorWPositions.py
- HardwareObjects/DESY/DigitalZoomMotor.py
- HardwareObjects/EMBL/EMBLDetector.py
- HardwareObjects/EMBL/EMBLMiniDiff.py
- HardwareObjects/EMBL/EMBLPiezoMotor.py
- HardwareObjects/EMBL/EMBLSlitBox.py
- HardwareObjects/EMBL/EMBLTableMotor.py
- HardwareObjects/EMBL/TINEMotor.py
- HardwareObjects/ESRF/ESRFMultiCollect.py
- HardwareObjects/ESRF/ID232BeamDefiner.py
- HardwareObjects/ESRF/ID30Light.py
- HardwareObjects/GrobMotor.py
- HardwareObjects/MAXIV/BIOMAXAperture.py
- HardwareObjects/MD2Motor.py
- HardwareObjects/MicrodiffMotor.py
- HardwareObjects/MicrodiffSamplePseudo.py
- HardwareObjects/MotorWPositions.py
- HardwareObjects/RobodiffLight.py
- HardwareObjects/RobodiffMotor.py
- HardwareObjects/RobodiffMotorWPositions.py
- HardwareObjects/SOLEIL/PX1/PX1DetectorDistance.py
- HardwareObjects/SOLEIL/PX2/PX2Resolution.py
- HardwareObjects/SOLEIL/SOLEILEnergyScan.py
- HardwareObjects/SOLEIL/TangoDCMotor.py
- HardwareObjects/SardanaMotor.py
- HardwareObjects/SpecMotorWPositions.py
- HardwareObjects/SpecMotorWSpecPositions.py
- HardwareObjects/abstract/AbstractMotor.py
- HardwareObjects/mockup/BeamlineActionsMockup.py
Replaced def move with def _set_value
Replaced move calls with set_value calls
Replaced userName() calls with use of username attribute
Replaced zoom_supported with read_only
A few mockups and complex motors still not complete.
> Refactored move, userName()

- HardwareObjects/mockup/MotorMockup.py
Simplified MotorMockup
@marcus-oscarsson I know it is a bit irritating that I am refactoring what you just put in. My version is a bit simpler. But the main reason is that (from experience) I think that people will be using the mockups, and especially this one, which is nice and understandable,  as templates to understand and write their own. That makes it important that this is following the letter and spirit of the AbstrctActuator. And that is that set_value should be left unchanged, and that _set_value should be the function that takes care of the actual motor moves.
Anyway, feel free to reject it if you like.
> Simplified MotorMockup

- HardwareObjects/abstract/AbstractMotor.py
- HardwareObjects/mockup/MotorMockup.py
Added specific states and  handling of move timeouts to MotorMockup.
Expanded MotorStates.
MotorStates is still not settled, but I think that as a minimum we will need two additional states, READY and UNKNOWN. Further additions can be looked at later, if required.
> MotorMockup fix

- HardwareObjects/mockup/ShutterMockup.py
- configuration/xml-qt/fast-shutter-mockup.xml
- configuration/xml-qt/safety-shutter-mockup.xml
This was debugging code, that I just forgot to clean up. Apologies
> Made ShutterMockup an AbstractNState

- HardwareObjects/MicrodiffZoom.py
- HardwareObjects/mockup/MicrodiffZoomMockup.py
Dear all,
I made a new  mockup for the MicrodiffZoom using AbstractNState as my original version seems to have disappeared in the refactoring ... 
I've also made a few minor changes to the Exporter implementation
Cheers,
Marcus
> MicrodiffZoom using AbstractNState - Mockup and Exporter implementation

- HardwareObjects/abstract/AbstractActuator.py
- HardwareObjects/mockup/MotorMockup.py
- test/pytest/test_detector.py
Fixed bug in MotorMockup._move, and another one in detector_test.
pytest now passes
Added more informatoin to test messages (it is easier if you can see how the value is wrong)
> Motor mockup and testing fix

- HardwareObjects/mockup/MotorMockup.py
This should hopefully have the proper timeout behaviour, also for timeout = 0.
Review very much needed.
On closer inspection you really *do* need to override set_value to get this to work properly, like Marcus coded it originally (sorry, Marcus).
> [CODE CAMP] MotorMockup

- HardwareObjects/abstract/AbstractActuator.py
It fails to check limits containing the value 0.
> [Fix] bug in check limits

- HardwareObjects/abstract/AbstractActuator.py
Sorry, last fix was not correct, thanks @rhfogh !
@beteva , sorry for the inconvinience.
> [Fix] re-fix statement in AbstractActuator

- BaseHardwareObjects.py
- HardwareObjectFileParser.py
- HardwareObjects/MultiplePositions.py
- HardwareObjects/SOLEIL/PX1/PX1Configuration.py
Documented relevant classes
Also added fixes to satisfy pylint, and a few TODO suggestions (hence additional files)
> [CODE CAMP] BaseHardwareObjects

- HardwareObjects/mockup/MicrodiffZoomMockup.py
- configuration/xml-web/udiff_zoom.xml
> [ISSUE 520] - Python2.7 and 3 compatibility fix

- HardwareObjects/mockup/NStateMockup.py
- configuration/test/beamline_config.yml
- configuration/test/safety-shutter-mockup.xml
- test/pytest/test_shutter.py
> Add safety shutter

- HardwareObjects/EMBL/EMBLBeamCentering.py
- HardwareObjects/EMBL/EMBLMiniDiff.py
- HardwareObjects/EMBL/EMBLTableMotor.py
- HardwareObjects/GrobMotor.py
- HardwareObjects/mockup/DiffractometerMockup.py
- HardwareObjects/mockup/EnergyMockup.py
- HardwareObjects/mockup/ShutterMockup.py
- test/pytest/test_shutter.py
Dear all,
Fixed a few smaller bugs.
Cheers,
Marcus
> Minor bug fixes

- HardwareObjects/MicrodiffZoom.py
- HardwareObjects/mockup/MicrodiffZoomMockup.py
Mockup handles specific values format.
> MicrodiffZoom handles B-Zoom and MotorisedZoom.

- HardwareObjects/BlissMotor.py
Get status from bliss motor on init.
Fixed issues with states : make update_state function work with different types of 'state' input parameter ( bliss states, HWRObject states, specific_states ... )
> Fixed BlissMotor issues to work with MotorSpinBoxESRFBrick

- HardwareObjects/SardanaMotor.py
- HardwareObjects/abstract/AbstractActuator.py
- HardwareObjects/abstract/AbstractNState.py
Replaces #530 .
Due to multiple additional commits and merges in 530 this is a new, clean PR with the same content.
> Fix update values v2

- HardwareObjects/BlissMotor.py
Changed update_state to _update_state. Implemented get_state and get_specific_state.
Closes pull requests #533 and #537
> BlissMotor

- configuration/test/sample-changer-mockup.xml
Hi
Just added missing configuration files.
Cheers,
Marcus
> [CODE CAMP][AbstractSampleChanger] - Added missing configuration file

- configuration/test/beamline_config.yml
- configuration/test/diff-kappa-mockup.xml
- configuration/test/diff-kappaphi-mockup.xml
- configuration/test/diff-omega-mockup.xml
- configuration/test/diff-phiy-mockup.xml
- configuration/test/diff-phiz-mockup.xml
- configuration/test/diff-sampx-mockup.xml
- configuration/test/diff-sampy-mockup.xml
- configuration/test/diffractometer-mockup.xml
- test/pytest/TestAbstractActuatorBase.py
- test/pytest/TestAbstractMotorBase.py
- test/pytest/TestAbstractNStateBase.py
- test/pytest/test_beam.py
- test/pytest/test_omega_motor.py
- Added comments (as requested by @marcus-oscarsson)
- Added test for wrap_range (required adding diffractometer_mockup and motors to test set=up)
- put test_beam into TestClasses framework
> Added comments and additional tests

- HardwareObjects/Bliss.py
- HardwareObjects/BlissActuator.py
- HardwareObjects/BlissMotorWPositions.py
- HardwareObjects/ESRF/Transmission.py
- HardwareObjects/MicrodiffLightBeamstop.py
Change ESRF/Transmission to use AbstractTransmission.
Added warning for few deprecated classes.
Change MicrodiffLightBeamstop to use ExporterNState.
> Bliss classes

- HardwareObjects/abstract/AbstractShutter.py
- HardwareObjects/mockup/ShutterMockup.py
Remove ShutterStates. Upgrade ShutterMockup to use AbstractShutter.
> AbstractShutter remove specific states

- HardwareObjects/abstract/AbstractResolution.py
Defines AbstractResolution as AbstractMotor. Implements distance_to_resolution and resolution_to_distance.
Resolves #450
> AbstractResolution class.

- HardwareObjects/abstract/AbstractDetector.py
Hello,
Added missing import removed by accident when resolving conflict
Marcus
> Added missing import

- test/pytest/TestAbstractMotorBase.py
Updated tests to avoid test errors in case of roundoff error when setting floats.
> Fixed test vulnerability to roundoff error

- HardwareObjects/Resolution.py
- HardwareObjects/abstract/AbstractDetector.py
- HardwareObjects/mockup/ResolutionMockup.py
Hi,
Two minor fixes to AbstractDetector and Resolution.
All the best,
Marcus
> Abstract detector and Resolution fixes

- HardwareObjects/Resolution.py
- HardwareObjects/abstract/AbstractResolution.py
Reverts mxcube/HardwareRepository#564
Something went wrong -the Resolution.py file is not the one I've pushed. Maybe resolving the conflict added the deleted by me code.
> Revert "Abstract resolution"

- HardwareObjects/QtTangoLimaVideo.py
- HardwareObjects/abstract/AbstractVideoDevice.py
Adding image decoding for video mode 'bayer_rg16' with QtTangoLimaVideo
> Decoding images for bayer_rg16 video mode

- HardwareObjects/BlissMotor.py
DISABLED has to be treated in priority.
> Changes in get_state to prioritise the certain states.

- HardwareObjects/LimaPilatusDetector.py
Fix a bug in the set_energy_threshold.
> Better handling of the Pilatus energy threshold.

- HardwareObjects/ESRF/BeamCmds.py
- HardwareObjects/ESRF/BlissHutchTrigger.py
Triggering actions to execute when enter/exit hutch. ESRF specific.
> Esrf hutchtrigger

- mxcubecore/HardwareObjects/Beamline.py
- mxcubecore/HardwareObjects/SOLEIL/PX2/PX2Collect.py
- mxcubecore/HardwareObjects/abstract/AbstractCollect.py
- mxcubecore/HardwareObjects/abstract/AbstractOnlineProcessing.py
- mxcubecore/HardwareObjects/mockup/CollectMockup.py
- mxcubecore/HardwareObjects/mockup/OnlineProcessingMockup.py
- mxcubecore/configuration/embl_hh_p14/beamline-setup.xml
- mxcubecore/configuration/embl_hh_p14/beamline_config.yml
- mxcubecore/configuration/embl_hh_pe2/beamline-setup.xml
- mxcubecore/configuration/lnls_manaca/beamline_config.yml
- mxcubecore/configuration/lnls_sol/beamline_config.yml
- mxcubecore/configuration/mockup/qt/beamline_config.yml
- mxcubecore/configuration/mockup/test/beamline_config.yml
- mxcubecore/configuration/mockup/web/beamline_config.yml
* Reverted abstract_collect and CollectMockup to working version.
* Replaced parallel_processing with online_processing
> [Bug] Reverted CollectMockup to working state

- mxcubecore/Command/Epics.py
- mxcubecore/HardwareObjects/LNLS/EPICSMotor.py
> Fixes on Epics.py and EPICSMotor class

- mxcubecore/HardwareObjects/LNLS/EPICSActuator.py
- mxcubecore/HardwareObjects/LNLS/EPICSMotor.py
Hi,
* On EPICSMotor: clean up, small fixes and the addition of a simple watch routine (to keep motor values updated on the UI);
* On EPICSActuator: clean up.
Thanks!
> EpicsMotor and Actuator: clean up and fixes

- mxcubecore/Command/exporter/StandardClient.py
- mxcubecore/HardwareObjects/EMBL/EMBLTableMotor.py
- mxcubecore/HardwareObjects/Gphl/GphlMessages.py
- mxcubecore/HardwareObjects/GphlWorkflow.py
- mxcubecore/HardwareObjects/LNLS/EPICSActuator.py
- mxcubecore/HardwareObjects/LNLS/EPICSMotor.py
- mxcubecore/HardwareObjects/QueueManager.py
- mxcubecore/HardwareObjects/abstract/AbstractSampleChanger.py
- mxcubecore/HardwareObjects/queue_entry.py
- mxcubecore/HardwareObjects/queue_model_objects.py
Reverted change to AbstractSampleChanger, and various improvements in GPhL-specific code.
NOTE: The change to AbstractSampleChanger is a temporary fix that reverts a commit from 15/10. The modified version did not register a sample mounted from the samplegrid in  app.CURRENTLY_MOUNTED_SAMPLE. Quite likely a more complex change is required to avoid reintroducing the problems that the previous change was supposed to solve.
> Rhfogh mxcube3

- requirements_python2.txt
- requirements_python3.txt
Added development requirements to requirements files
> Added development requirements to requirements files

- mxcubecore/HardwareObjects/Beamline.py
Testing release procedure by adding beamline property 
- Added beamline_action property to Beamline object
> Added beamline_action property to Beamline object

- doc/MEPS/MEP-01/mep01.md
Updated to include agreements of developers' meeting 20220222
> Rhfogh patch 1

- mxcubecore/HardwareObjects/GphlWorkflowConnection.py
- mxcubecore/HardwareObjects/QueueManager.py
- mxcubecore/HardwareObjects/abstract/AbstractXrayCentring.py
- mxcubecore/HardwareObjects/mockup/XrayCentringMockup.py
> Added AbstractXrayCentring and XrayCentringMockup

- mxcubecore/HardwareObjects/Gphl/GphlQueueEntry.py
- mxcubecore/HardwareObjects/abstract/AbstractCollect.py
- mxcubecore/HardwareObjects/mockup/SampleChangerMockup.py
After the many accumulated changes some fixes were needed before I could get mxcube3 to run in mock mode. It runs now, though. Great to be up at the bleeding edge!
> Bug fixes after recent GPhL and ESRF merges

- mxcubecore/HardwareObjects/GphlWorkflow.py
- mxcubecore/HardwareObjects/GphlWorkflowConnection.py
- mxcubecore/HardwareObjects/ISPyBRestClient.py
- mxcubecore/HardwareObjects/LimaPilatusDetector.py
- mxcubecore/HardwareObjects/QueueManager.py
- mxcubecore/HardwareObjects/abstract/AbstractXrayCentring.py
- mxcubecore/HardwareObjects/mockup/CollectEmulator.py
- mxcubecore/HardwareObjects/mockup/ISPyBRestClientMockup.py
- mxcubecore/HardwareObjects/mockup/SampleChangerMockup.py
- mxcubecore/HardwareObjects/mockup/XrayCentringMockup.py
- mxcubecore/HardwareRepository.py
This one is tested (on mock), brings GPhL workflow up to date, fixes some bugs, and improves error visibility in output. Goes with parallel PR in mxcube3.
> Rhfogh develop

- mxcubecore/HardwareObjects/abstract/AbstractResolution.py
- mxcubecore/HardwareObjects/mockup/ActuatorMockup.py
- mxcubecore/HardwareObjects/mockup/FluxMockup.py
- mxcubecore/HardwareObjects/mockup/MotorMockup.py
- mxcubecore/HardwareObjects/mockup/ResolutionMockup.py
- mxcubecore/configuration/mockup/detector-distance-mockup.xml
- mxcubecore/configuration/mockup/resolution-mockup.xml
- mxcubecore/configuration/mockup/test/beamline_config.yml
- test/pytest/TestAbstractActuatorBase.py
- test/pytest/TestAbstractMotorBase.py
- test/pytest/TestAbstractNStateBase.py
- test/pytest/TestHardwareObjectBase.py
- test/pytest/conftest.py
- test/pytest/test_beam.py
- test/pytest/test_dataobject.py
- test/pytest/test_detector.py
- test/pytest/test_energy.py
- test/pytest/test_flux.py
- test/pytest/test_mach_info.py
- test/pytest/test_resolution.py
- test/pytest/test_sample_changer.py
- test/pytest/test_transmission.py
Run black and pylint for all the file in test/pytest directory.
Apply python3 syntax.
> Test files cleanup
