BaseHardwareObjects.py
update_values method is used by qt brick to ensure that the brick gets necessary values on the startup.
See code for more info
=> 2016.08.03. Added update_values method

HardwareObjectFileParser.py, HardwareRepository.py
Added feature to redirect a xml to different xml. Feature allows to define a referemce (**hwr_import href**) to different xml. For example
* detector-mockup.xml:
```
<hwr_import href="/detector-mockup-pilatus"/>
```
* detector-mockup-pilatus.xml:
```
<equipment class = "DetectorMockup">
<tempThreshold>33.5</tempThreshold>
<humidityThreshold>20.0</humidityThreshold>
<tolerance>0.2</tolerance>
<type>pilatus</type>
<model>6M_F</model>
<manufacturer>DECTRIS</manufacturer>
<px>0.172</px>
<py>0.172</py>
<hasShutterless>True</hasShutterless>
<fileSuffix>cbf</fileSuffix>
</equipment>
```
If from the gui or hardware objects a **detector-mockup** is requested then **detector-mockup-pilatus** will be loaded.
This idea came up by switching detectors at beamline. Previously the only way was to rewrite …
=> 2016.06.19. Added feature to use nested xmls

HardwareObjects/MultiplePositions.py
Not sure why those changes are there, but it seems safer to call getState() instead of
relying on the state in stateChanged callback... It has been changed on our beamlines here
so I suppose it's a good change ?
=> Small changes in MultiplePositions Hardware Object

HardwareObjects/TangoShutter.py, HardwareRepository.py
The main goal of this commit is to change TangoShutter to either use commands configured in xml (as before) or if those are not configure, use the State channel as a read/write attribute.
=> TangoShutter (dual command - read-write attribute)

HardwareObjects/QueueModel.py, HardwareObjects/queue_entry.py, HardwareObjects/queue_model_objects_v1.py
Hey !
- Adding a easier way to reference the queue_model
- Added the possibility to set originating queue_id for nodes that was generated 
by third party software and have another origin than the node directly above it in the tree
Cheers,
Marcus
=> [2.2] Characterization related methods

BaseHardwareObjects.py, HardwareRepository.py
Added method to reload hardware objects.
Method is based on reimport package (sudo pip install reimport). It detects files that have been changed. Then these hwobj are disconnected from gui, reimported and connected back to gui.
After connection to gui `update_values` method is called to refresh gui.
Before reimporting all gevent greenlets needs to be stoped and in init relaunched.
This needs more testing
=> [master] 2017.07.28. Reload hardware objects

HardwareObjects/sample_changer/Cats90.py, HardwareObjects/sample_changer/CatsMaint.py, HardwareObjects/sample_changer/GenericSampleChanger.py
Add a new available signal in GenericSampleChanger.py for SampleChanger objects to emit
Modify heavily Cats90.py - NOTE:  the version in the repository previous to this commit is completely forced-adapted for its use in old MaxLab 911 beamline.  It could not be used anywhere else.   This commit tries to restore generality so that code can be used in other sites.  At the same time it introduces support for ISARA models and adapted general state handling for Cats (as it is used already in other beamlines) that takes into account Powered, Lid state and other DS state information
The CatsMaint.py also adds support for ISARA, plus a number of new methods aiming at a generic SampleChanger-Maintenance object to be used in mxcube3.  If this shows to be of general use (with other types of sample …
=> Cats changes

HardwareObjects/ISPyBClient2Mockup.py
Why making it more complicated?
=> ISPyBClient2Mockup: anything else than 'idtest000' is considered a wrong login id

HardwareObjects/GenericVideoDevice.py
Add useqt property from xml to decide whether to use qt (qimage) or not for video encoding
Add scale property from xml so that classes can use on reading of images
Fix a bug where if cam_type was not specified, the wrong variable was assigned the default_cam_type
=> GenericVideoDevice allows for non-qt encoding

HardwareObjects/EdnaWorkflow.py, HardwareObjects/XMLRPCServer.py
This is the PR for issue #76. It implements secure XMLRPC communication based on a token. 
The security is disabled by default, and can be enabled by adding "`<enforceUseOfToken>True</enforceUseOfToken>`" to the XMLRPC configuration XML file.
The token is passed from the EdnaWorkflow HO to the class SecureXMLRpcRequestHandler via a static call. It's working but maybe can be made more elegantly?
I have tested this code on MASSIF 1 on 2017/09/20, and it's working as expected.
If this PR is accepted I'll add similar PRs for the branches 2.1 and 2.2.
=> Improved XMLRPC security.

HardwareObjects/AbstractMultiCollect.py, HardwareObjects/Microdiff.py, HardwareObjects/MiniDiff.py
diffractometer.wait_ready() is called by AbstractMultiCollect at the end of a data collection,
this mainly concerns MD2/3(UP).
=> Add wait_ready() function for diffractometers

HardwareObjects/XMLRPCServer.py
The absence of a check for timeout when waiting for the centre beam procedure to finish is deliberate - if the procedure don't finish something is wrong with mxCuBE and manual intervention is needed anyway.
=> Issue #115: added new method for centre beam

HardwareObjects/Shapes.py
Hi
- Taking care of an issue pointed out by @rhfogh in #135
-  Using the labels Point, Line and Grid (by default) instead of P, L, and G mainly to avoid confusion with space groups in the case of Points, i.e. P1, P2 and so on.
Marcus
=> [2.2] Shapes fix

HardwareObjects/queue_entry.py
Tries to solve #153 
In the current Qt4 implementation it is not possible to start a centering while the SampleQueueEntry is executed because at the beginning of each queue entry a signal queue_entry_execute_started is send that via Qt4_TreeBrick disables all widgets (except TreeBrick). Also I am not sure if a forced sample centering after the sample mount is so important (sample could be in a bad shape, no need to continue).
=> [master] Fix for issue #153

HardwareObjects/AbstractCollect.py, HardwareObjects/CollectMockup.py, HardwareObjects/EMBL/EMBLCollect.py, HardwareObjects/MAXIV/BIOMAXCollect.py, HardwareObjects/SOLEIL/PX2Collect.py
Bug fix of AbstractCollect
I took the opportunity of running the pycharm syntax checking and cleaning things up as well, with consequences for AbstractCollect subclasses.
Comments:
1) AbstractCollect.do_collect triggered 'collection failed' whether the collection failed or succeded
- Are you sure you that was tested before it was checked into master?
2) do_collect did not close the shutters if there was an error during collection, the way other collection routintes did. Surely this was worth fixing
3) Changed the 'with cleanup' to a plain 'try: ...except: .. finally'. It can be changed back if needed, but when the context manager cannot be reused the two are equivalent, the 'with' construction saves no repetitions, and  the plain 'try: except' is simpler and easier to understand (less …
=> Bugfix and clean-up of AbstractCollect

CommandContainer.py, HardwareObjects/GenericDiffractometer.py
NB The log output for missing channels is still excessively visible.
See issue #169 
This change avoids an unnecessary error raised (which is anyway covered by except: pass) and reduces teh log level from exception to error.
=> Cleaned error output and reduced missing channel visibility.

HardwareObjects/MicrodiffMotor.py
-- look for channel and command definition in the configuration file first, fall back to in-place definition if missing (this makes it possible to use the same class for different protocols: e.g. tango, exporter, tango_events ...)
-- modifications to state related methods
-- state no 2 does not seem to correspond to UNUSABLE -- there may be a better way around this ...
-- get_limits() == getLimits()
=> Microdiff motor modifs

HardwareObjects/ISPyBClient2.py, HardwareObjects/SOLEIL/SOLEILISPyBClient.py
-- changing leading '__' to single underscore
self._shipping
self._collection
self._tools_ws
self._translations
self._disabled
This is to allow for easier subclassing -- attributes are not easily accessible in children when subclassing due to special treatment defined in BaseHardwareObjects.
Or may there be a workaround I have not thought about ?
=> ISPyBClient2.py and SOLEILISPyBClient

HardwareObjects/GphlWorkflow.py, HardwareRepository.py, __init__.py
Changed so setting is done only in one place, environment variables are not overridden, and bin/mxcube has no hardwiring.
Also GPhL-specific bug fix
=> Cleaned up setting of HO and brick pythonpath and HWRserver

HardwareRepository.py
Cleaned up the loadHardwareObject method
After finishing of gui load print a table with info about all hwobj. like:
```
+ ===================================================================== +
| Xml                      | Class                      | Load time| Comment|
+ ===================================================================== +
| /eh1/diff-omega          | MotorMockup                | 1 ms     |    |
| /Qt4_video-mockup        | Qt4_VideoMockup            | 4 ms     |    |
| /eh1/diff-sampy          | MotorMockup                | 0 ms     |    |
| /eh1/diff-sampx          | MotorMockup                | 0 ms     |    |
| /eh1/diff-phiz           | MotorMockup                | 0 ms     |    |
| /eh1/diff-phiy           | MotorMockup                | 0 ms     |    |
| …
```
=> [master] Cleanup the loadHardwareObject method

HardwareObjects/BeamlineSetup.py, HardwareObjects/DataAnalysis.py, HardwareObjects/GenericVideoDevice.py, HardwareObjects/LimaVideo.py, HardwareObjects/Qt4_VideoMockup.py, HardwareRepository.py, HardwareRepositoryBrowser.py
Fixed bug in image width and height handling that broke the VideoMockup.
NB height and width handling is inconsistent - see relevant Issue.
Replaced getHardwareRepositoryPath with (already existing) findInRepository, as the former did not work with multi-directory repository paths.
=> Video bugfix

HardwareObjects/MicrodiffMotor.py
-- fix typo if not self.get_max_spped_cmd: -> if not self.get_max_speed_cmd:
-- add translate directory to translate microdiff states to states defined
in AbstractMotor -- using so far unused self.motor_states instance.
The reason we need this is that integer representation of microdiff state
do not correspond to the integer representation of AbstractMotor (and bricks)
in general.
For instance when MD2 motors are in Ready state self.state_attr.getValue()
returns 'Ready', but MicrodiffMotor.READY is 2  which designates state 'OFF' 
of the AbstractMotor.
-- state is currently updated via two signals: 'update' and 'stateChanged'
there was inconsistency between the two:
the call defined in connectNotify was calling self.motorStateChanged()
using self.get_state() as parameter which returns …
=> Microdiff motor state

HardwareObjects/BeamlineSetup.py, HardwareObjects/DESY/Centring.py, HardwareObjects/DESY/DigitalZoomMotor.py, HardwareObjects/DESY/MjpgStreamVideo.py, HardwareObjects/DESY/NanoDiff.py, HardwareObjects/DataAnalysis.py, HardwareObjects/GenericVideoDevice.py, HardwareObjects/GphlWorkflow.py, HardwareObjects/GphlWorkflowConnection.py, HardwareObjects/LimaVideo.py, HardwareObjects/MotorWPositions.py, HardwareObjects/Qt4_VideoMockup.py, HardwareObjects/Session.py, HardwareRepository.py, HardwareRepositoryBrowser.py
- Replaced getHardwareRepositoryPath with (pre-existing) findInRepository, as the former did not work with multi-directory hardware repositories.
- Added facility to override data directory paths. This allows you to use a beam-line-specific session.xml in mock mode, redirecting teh data to the correct location on the mocking computer. The change has no effect if the relevant configuration file is absent.
- Changed GPhL configuration handling
=> Changed configuration handling

.pylintrc, HardwareObjects/mockup/CollectEmulator.py, configuration/embl_hh_p14/gphl_beamline_config/instrumentation.nml
This (proposal for discussion) enables all pylint checks. I think we should start there, and only
disable them in each case when we decide the check should be (temporarily?) ignored. The newly added checks do not dominate the output (see below)
It also disables the 'bad-continuation' check  (C0330 'Wrong continued indentation before block'). 
The problem is that the format generated by black causes a pylint error. According to https://github.com/PyCQA/pylint/issues/289 this is due to a pylint bug that goes back to 2014 and stillis not fixed. The solution seems to be to diable the check and rely on black to get the formatting we want.
For information I ran pylint (off-line) on all of HardwareRepository after making the change. There  are no bad-continuation errors at all. The most common …
=> Proposed pylint change (and minor gphl fixes)

.pylintrc
Based on the https://stackoverflow.com/questions/1899436/pylint-unable-to-import-error-how-to-set-pythonpath this is fixing the Unable to import error.
=> Fix for pylint, codacy

HardwareObjects/SOLEIL/PX2/PX2Diffractometer.py
Updated PX2Diffractometer, now includes refractive optical alignment model.
The environment model is that of a transparent planparallel slab. To fit the image movement model we need three parameters to describe the circle on which the sample is really moving and four additional parameters to account for refractive shift of apparent sample position:: thickness of the slab, normal of the slab planes, index of refraction and position of the sample in the slab.
The fitting is done using Nelder-Mead algorithm as implemented in lmfit.minimize. The advantage of lmfit version is that it allows for specification of constraints on the fitted parameters. This is important to make the procedure work robustly in practice.
The minimum number of points (clicks) is 7 but I would recommend using more …
=> Add refractive model alignment to PX2Diffractometer.py

HardwareObjects/QtGraphicsLib.py
This fixes problem with grid drawing starting from arbitrary corner. Only touches QtGraphicsLib.py
Modification of update_grid_draw_parameters() method. Trick used is to create a local copy of start and end coordinates, then to swap any of them when the end one is smaller then the start one. A few additional formatting changes are due to applying autopep8 and black on the file.
=> Fix grid drawing

HardwareObjects/EMBL/EMBLAperture.py, HardwareObjects/EMBL/EMBLFlux.py, HardwareObjects/MAXIV/BIOMAXAperture.py, HardwareObjects/MicrodiffAperture.py, HardwareObjects/UnitTest.py, HardwareObjects/abstract/AbstractAperture.py, HardwareObjects/mockup/BeamInfoMockup.py
Dear all,
Noticed that one commit was missing from the previous PR #407, sorry,
So we finally agreed on removing the unit from the method name but that the
methods would return the same unit, on all sites, defined by AbstractAperture.
Either mm or microns which is a decision that remains be taken.
Regards,
Marcus
=> Removed unit in method name

BaseHardwareObjects.py, HardwareObjects/Beamline.py, HardwareObjects/EMBL/EMBLBeamline.py
With this PR, you can set up and configure procedures in the same way as any other hardware object.
To register the object as a procedure you add its name to
Beamline._procedure_names.
The ConfiguredObject.procedures property will give you a dictionary of all configured procedures - notice that the resulting dictionary is a copy and modifying it will not modify the object internals. 
The same machinery could be used to add procedures to other classes (like DIffractometer?) if desired.
=> Added support for procedures

HardwareObjects/mockup/ISPyBClientMockup.py
Making the necessary changes to ISPyBClientMockup so that it corresponds to the real object (now containing a ISPYBRestClient reference as lims_rest)
Marcus
=> Minor update to ISPyBClientMockup

HardwareObjects/Beamline.py, HardwareObjects/abstract/AbstractProcedure.py, HardwareObjects/datamodel/__init__.py, HardwareObjects/datamodel/common.py, HardwareObjects/datamodel/data_model_py2.py, HardwareObjects/datamodel/data_model_py3.py, HardwareObjects/mockup/MockProcedure.py, configuration/test/beamline_config.yml, configuration/test/mock_procedure.yml, requirements_python3.txt, test/pytest/conftest.py, test/pytest/test_procedure.py
Dear all,
Updated the AbstractProcedure according to the conclusions of the developers meeting.
- Mainly making it possible to user either data classes (for Python 3) or using dictionaries                
(for Python 2)
- Using the commonly agreed names for the states defined as ProcedureState. ProcedureState will disappear as the state definition is inherited from HardwareObject, but that PR is not merged yet so ProcedureState serves as a placeholder.
The data models are stored in the datamodels sub folder and the correct module is imported depending on python version. The data models are for simplicity kept in two separate files with the _py[version] suffix but this could be changed to folders if one would like some hierarchical structure.
The Python 2 data model is simply a dict with …
=> Changed AbstractProcedure so that it uses data classes in Python3 and dictionaries in Python2

HardwareObjects/abstract/AbstractVideoDevice.py
Added y16_2_rgb function to other encoding options ( y8_2_rgb, yuv_2_rgb ...)
The cv2.cvtColor() function's call parameters maybe to be reviewed ( didn't found anything in OpenCV options that matched better ):
return cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
=> y16 to rgb encoding option added

HardwareObjects/QtGraphicsLib.py, HardwareObjects/QtGraphicsManager.py
Bug discovered using CameraBrick.py
If HWR.beamline.microscope <=> QtGraphicsManager then
The widget to display images is :
QtGraphicsManager.graphics_view and the scene, the GraphicsView.graphics_scene 
When the widget is 'small' and fits the scene surface (and not more), their coordinates ( QGraphicsView's and QGraphicScene's ) are visually the same, but if the view is bigger than the scene, there's a delta between them ( ex: GraphicsItemCentringLines drawn far from the mouse position ).
One solution to fix this: all the positions related to scene's coordinates
=> Using QGraphicsScene coordinates rather than QGraphicsView ones

HardwareObjects/ExporterNState.py, HardwareObjects/Microdiff.py, HardwareObjects/MicrodiffZoom.py, HardwareObjects/abstract/AbstractNState.py
Dear all,
This is a simplified version of the AbstractNState object, it simply provides the means to define
N discrete states that needs to be defined in the subclass. I've made an example implementation for the micro diffractometer zoom (testing with the BZoom). 
It's not as flexible and configurable as the original version but is simpler and provides perhaps a more well defined interface. Objects like shutters or beam stops then have to be implemented as separate objects with clearly defined open/closed in/out states the values however needs to be mapped to the actual hardware.
Marcus
=> [WIP] Simplified version of AbstractNState

HardwareObjects/InstanceServer.py
If widget is an objectof type pyqtgraph.widgets.PlotWidget.PlotWidget
and the target attribute in hasattr does not exists a NameError exception
is raised.
=> Protect from nested raise exception

HardwareObjects/MicrodiffAperture.py, HardwareObjects/abstract/AbstractShutter.py, HardwareObjects/mockup/ShutterMockup.py
Change the MicrodiffAperture to inherit from ExporterNstate rather than ExporterMotor.
I want to ask @all if aperture in/out action should in this class, or treated by a separate class.
Being a separate class is easier as it will be a simple ExporterNState, with the standard set/get_value methods. If we put it here, we would need an extra set/get_in.
=> MicrodiffAperture inherit from ExporterNState instead of ExporterMotor.

HardwareObjects/abstract/AbstractDetector.py, HardwareObjects/abstract/AbstractResolution.py
@beteva 
Proposal to refactor AbstractResolution relative to your abstract_resolution PR #556  that avoids using detector metadata in resolution without putting the wavelength into the detector. The formulae look slightly different, but I think they are OK.
It took a new function, AbstractDetector.get_outer_radius; we can certainly call it something else, but I think it at least fits naturally within the detector.
What do you think?
(NB I have not run tests)
=> Refactoring resolution and detector distance relative to PR #556

HardwareObjects/BlissShutter.py
Do not update self._nominal_value, prevents GUI from update the state.
=> Do not update self._nominal_value

HardwareObjects/abstract/AbstractDetector.py, HardwareObjects/abstract/AbstractResolution.py
Fix the detector radius to be the min(width/2, height/2) if no distance argument in get_radius. The  get_radius with no argument is used to calculate resolution to distance.
Raise RuntimeError if no distance for outer radius -  cannot calculate the radius if both distance argument and distance motor are None.
Fixed bug in force_emit_signals.
Run black. Add documentation.
=> Detector radius fix

HardwareObjects/Beamline.py
The Qt widget create_discrete_widget requires this **run_online_processing** boolean value on its initialization.
=> Missing member in Beamline object

mxcubecore/HardwareObjects/LNLS/EPICSMotor.py, mxcubecore/configuration/lnls_manaca/dtox.xml, mxcubecore/configuration/lnls_manaca/udiff_kappa.xml, mxcubecore/configuration/lnls_manaca/udiff_kappaphi.xml, mxcubecore/configuration/lnls_manaca/udiff_omega.xml, mxcubecore/configuration/lnls_manaca/udiff_phix.xml, mxcubecore/configuration/lnls_manaca/udiff_phiy.xml, mxcubecore/configuration/lnls_manaca/udiff_phiz.xml, mxcubecore/configuration/lnls_manaca/udiff_sampx.xml, mxcubecore/configuration/lnls_manaca/udiff_sampy.xml, mxcubecore/configuration/lnls_sol/dtox.xml, mxcubecore/configuration/lnls_sol/udiff_kappa.xml, mxcubecore/configuration/lnls_sol/udiff_kappaphi.xml, mxcubecore/configuration/lnls_sol/udiff_omega.xml, mxcubecore/configuration/lnls_sol/udiff_phix.xml, mxcubecore/configuration/lnls_sol/udiff_phiy.xml, mxcubecore/configuration/lnls_sol/udiff_phiz.xml, mxcubecore/configuration/lnls_sol/udiff_sampx.xml, mxcubecore/configuration/lnls_sol/udiff_sampy.xml
Hi,
This PR changes the EPICS PVs used by EPICSMotor.py to check limits.
HLM and LLM fields are more straight-forward parameters for this than DHLM and DLLM.
Thanks,
Laís
=> Replace fields DHLM and DLLM with HLM and LLM

mxcubecore/HardwareObjects/Resolution.py
The precision depends on the difference between the current resolution and the target value - the smaller the difference, he better the precision.
Move twice to get the closet possible to the requested resolution
=> Define set_value for better precision.

mxcubecore/HardwareObjects/BlissMotor.py, mxcubecore/HardwareObjects/ExporterMotor.py
- Overriding name method gives unexpected names for exporter motors
=> Removed name override

mxcubecore/HardwareObjects/QueueManager.py
The problem described in #895 is due to a retry mechanism in the client that re-sends a request if there are no response after a certain amount of time. The call to `execute_entry` is in the case of #895 blocking so a retry is made after n minutes, effectively calling the entry twice (or even more depending on the duration of the call)
A parameter `_async` to make the call non-blocking was added, the task is executed in a greenlet if `_async` is passed `True`. The default behavior is to still that `execute_entry ` is blocking, so all logic that need a non blocking behavior need to set  `_async` to `True`
=> Patch for issue #895

mxcubecore/HardwareObjects/BlissNState.py, mxcubecore/HardwareObjects/Microdiff.py, mxcubecore/HardwareObjects/MiniDiff.py, mxcubecore/HardwareObjects/XMLRPCServer.py
Fix set_light_in/out, used by XMLRPC.
Change obsolete call in MiniDiff
Handle property coming from bliss actuator.
=> Handle light

mxcubecore/BaseHardwareObjects.py, mxcubecore/HardwareObjects/Beamline.py, mxcubecore/HardwareObjects/BeamlineActions.py, mxcubecore/HardwareObjects/GenericDiffractometer.py, mxcubecore/HardwareObjects/abstract/AbstractDetector.py, mxcubecore/HardwareObjects/mockup/BeamlineActionsMockup.py, mxcubecore/HardwareObjects/mockup/DetectorMockup.py, mxcubecore/HardwareObjects/mockup/DiffractometerMockup.py, mxcubecore/configuration/mockup/detector-mockup.xml, mxcubecore/configuration/mockup/diffractometer-mockup.xml, mxcubecore/utils/conversion.py
Adds a feature that allows any type hinted member of a HardwareObject to be exported to the UI. 
A function written with type hints for instance;
`    
def my_fancy_function(self, speed: float, num_images:int, exp_time:float, phase:PhaseEnum) -> bool:
return True
`
can now be exported so that a default UI can be displayed to the user, once validated the data entered
are passed to member in question.
Example of UI for the example below, illustrating the feature.
This feature is currently used in two places, it replaces the current beamline actions in MXCuBE 3
sot that they can be expressed as objects with type hinted members. It further makes it possible to
create simple maintenance UIs like the example above.
The type annotated beamline actions currently handles return data and errors …
=> Exposing type hinted attributes for UI

mxcubecore/HardwareObjects/ESRF/ESRFPhotonFlux.py, mxcubecore/HardwareObjects/MicrodiffAperture.py
Put the aperture in when setting its value. Improve style.
Resolves #682.
=> Allow the aperture factor to be other than a float.

mxcubecore/HardwareObjectFileParser.py
Bug has been introduced (when?), so it was only possible to do self.get_roles(). This PR sets back the lost functionality self["xxx"].get_roless(), when reference objects are defined as:
```
<object class=MyObject>
<xxx>
<object role=aaa href=/my_reference_object1 />
<object role=bbb href=/my_reference_object2 />
</xxx>
</object>
```
=> Bug fix when parsing reference objects

mxcubecore/HardwareObjects/TangoLimaVideoDevice.py, mxcubecore/HardwareObjects/abstract/AbstractVideoDevice.py
After moving to python 3, Lima camera was causing problems, because `AbstractVideoDevice.get_jpg_image` was using `cStringIO` which was deprecated in py3.
I'm creating this MR on behalf of MAX-IV. @meghdadyazdi is a reviewer
=> Refactor lima cameras
